### ISSUE TITLE
Consider changing license?

### ISSUE THREAD

**Issue by smitchelus** [fommil/openssh-java#7]
First off, thanks for putting this library together. It was exactly what I happened to need for my current project. However, I was wondering if it would be possible to change the licensing of this project to something like MIT or Apache v2? LGPL makes some corporate lawyers quite nervous.

It doesn't appear that any of your dependencies are licensed in such a way that the more liberal license would be an issue.

Thanks for your consideration.

**Comment by fommil** [comment]
Absolutely no way. I am a strong believer in copyleft and corporate lawyers who are nervous about the LGPL are turning away great software... there is plenty of precedent in the JVM world and plenty of precedent for GPL applications. I'm simply not interested in engaging with such entities.

You mean to ask for a more "permissive" licence. A more liberal license would be the GPL.
